mediamapper/urls.py
from django.http import HttpResponse
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS admin
    url(r'^admin/',  include(admin.site.urls)), # admin site
    url(r'^select2/', include('select2.urls')), # select2 multiselect admin
    url(r'^home/', view=TemplateView.as_view(template_name="medioschile/index.html"), name='home'),
    url(r'^api/', view=TemplateView.as_view(template_name="api.html"), name='api'),
    url(r'^medioschile/', include('medioschile.urls', namespace='medioschile')), # medioschile
    url(r'^medioscolombia/', include('medioscolombia.urls', namespace='medioscolombia')), # medioscolombia
    url(r'^redactor/', include('redactor.urls')), # redactor editor
    url(r'^search/', include('haystack.urls')),

)	+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medioschile/urls.py
from . import views
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from rest_framework import routers
from medioschile import serializers

router = routers.DefaultRouter()
router.register(r'propietarios', views.PropietarioViewSet)
router.register(r'sociedades', views.SociedadViewSet)
router.register(r'tiposociedades', views.TipoSociedadViewSet)
router.register(r'grupos', views.GrupoViewSet)
router.register(r'paises', views.PaisSociedadViewSet)
router.register(r'fuentes', views.FuenteViewSet)
router.register(r'escritos', views.EscritoViewSet)
router.register(r'canaltvs', views.CanalTVViewSet)
router.register(r'generoradios', views.GeneroRadioViewSet)
router.register(r'generoescritos', views.GeneroEscritoViewSet)
router.register(r'generocanaltvs', views.GeneroCanalTVViewSet)
router.register(r'generomediodigitales', views.GeneroMedioDigitalViewSet)
router.register(r'radios', views.RadioViewSet)
router.register(r'mediodigitales', views.MedioDigitalViewSet)
router.register(r'ejecutivos', views.EjecutivoViewSet)
router.register(r'empresarios', views.EmpresarioViewSet)
router.register(r'articulos', views.ArticuloViewSet)
router.register(r'autores', views.AutorViewSet)

urlpatterns = [
	url(r'^index/$', 'medioschile.views.index', name='index'),
    url(r'^acercade/$', 'medioschile.views.acercade', name='acercade'),
	url(r'^consultadirecta/$', 'medioschile.views.consultadirecta', name='consultadirecta'),
    url(r'^metodologia/$', 'medioschile.views.metodologia', name='metodologia'),
    url(r'^privacidad/$', 'medioschile.views.privacidad', name='privacidad'),
    url(r'^datos/$', 'medioschile.views.datos', name='datos'),
    url(r'^codigo/$', 'medioschile.views.codigo', name='codigo'),
    url(r'^contacto/$', 'medioschile.views.contacto', name='contacto'),
    url(r'^aporta/$', 'medioschile.views.aporta', name='aporta'),
    url(r'^analisiscl/$', 'medioschile.views.analisiscl', name='analisiscl'),
    url(r'^analisiscol/$', 'medioschile.views.analisiscol', name='analisiscol'),
    url(r'^fuente/$', views.FuenteList.as_view(), name='fuenteslist'),
    url(r'^analisis/$', views.AnalisisList.as_view(), name='analisislist'),
    url(r'^analisis/(?P<pk>\d+)/$', views.AnalisisDetail.as_view(), name='analisisdetail'),
    url(r'^regulacion/$', views.RegulacionList.as_view(), name='regulacioneslist'),
    url(r'^regulacion/(?P<pk>\d+)/$', views.RegulacionDetail.as_view(), name='regulaciondetail'),
    url(r'^grupo/(?P<pk>\d+)/$', views.GrupoDetail.as_view(), name='grupodetail'),
    url(r'^grupo/$', views.GrupoList.as_view(), name='gruposlist'),
    url(r'^propietario/$', views.PropietarioList.as_view(), name='propietarioslist'),
    url(r'^propietario/(?P<pk>\d+)/$', views.PropietarioDetail.as_view(), name='propietariodetail'),
    url(r'^escritolist/$', views.EscritoList.as_view(), name='escritoslist'),
    url(r'^escritolist/(?P<pk>\d+)/$', views.EscritoDetail.as_view(), name='escritodetail'),
    url(r'^canaltvlist/$', views.CanalTVList.as_view(), name='canalestvlist'),
    url(r'^canaltvlist/(?P<pk>\d+)/$', views.CanalTVDetail.as_view(), name='canaltvdetail'),
    url(r'^radiolist/$', views.RadioList.as_view(), name='radioslist'),
    url(r'^radiolist/(?P<pk>\d+)/$', views.RadioDetail.as_view(), name='radiodetail'),
    url(r'^mediodigitallist/$', views.MedioDigitalList.as_view(), name='digitaleslist'),
    url(r'^mediodigitallist/(?P<pk>\d+)/$', views.MedioDigitalDetail.as_view(), name='digitaldetail'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

templates/mediamapper/base.html
{% load staticfiles %}
{% load medioschile_extras %}
{% load medioscolombia_extras %}
<html lang="es">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<link rel="stylesheet" type="text/css" href="{% static 'css/mediamapper.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/application.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.tableTools.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/stacktable.css' %}" />
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<title>{% block title %}Mapa de Medios{% endblock %}</title>
</head>

<body>

  <header>
      <div class="row">
        <div class="col16">
          <h2 class="mapademedios">
            <a href="{% url 'medioschile:index' %}">Mapa de medios</a>
          </h2>
          <a href="#" class="main-nav-mobile collapsed" data-toggle="collapse" data-target="#wrap-mobile-navigation">
            <i class="icon icon-16 flaticon stroke menu-3"></i> Mostrar menu
          </a>
          <div id="wrap-mobile-navigation" class="wrap-mobile-navigation collapse">
            <nav>
              <ul>
                <li class="item-li"><a href="{% url 'medioschile:acercade' %}" class="item">Acerca de</a></li>
                <li class="item-li dropdown-nav with-count dropdown">
                  <a href="#" data-toggle="dropdown" class="dropdown-toggle item">Medios Chile <span class="arrow"></span></a>
                  <ul class="dropdown-menu">
                <li><a href="{% url 'medioschile:digitaleslist' %}"><span>{% contardigitales %}</span>Medios Digitales</a></li>
                <li><a href="{% url 'medioschile:escritoslist' %}"><span>{% contarescritos %}</span>Impresos</a></li>
                <li><a href="{% url 'medioschile:canalestvlist' %}"><span>{% contarcanalestv %}</span>Televisión</a></li>
                <li><a href="{% url 'medioschile:radioslist' %}"><span>{% contarradios %}</span>Radio</a></li>
                <li><a href="{% url 'medioschile:gruposlist' %}"><span>{% contargrupos %}</span>Grupos de Medios</a></li>
                <li><a href="{% url 'medioschile:propietarioslist' %}"><span>{% contarpropietarios %}</span>Propietarios</a></li>
                <li><a href="{% url 'medioschile:regulacioneslist' %}"><span>{% contarleyes %}</span>Legislación</a></li>
                <li><a href="{% url 'medioschile:fuenteslist' %}"><span>{% contarfuentes %}</span>Fuentes Utilizadas</a></li>
                  </ul>
                </li>
                <li class="item-li dropdown-nav with-count dropdown">
                  <a href="#" data-toggle="dropdown" class="dropdown-toggle item">Medios Colombia <span class="arrow"></span></a>
                  <ul class="dropdown-menu">
                <li><a href="{% url 'medioscolombia:digitaleslist' %}"><span>{% contardigitalescol %}</span>Medios Digitales</a></li>
                <li><a href="{% url 'medioscolombia:escritoslist' %}"><span>{% contarescritoscol %}</span>Impresos</a></li>
                <li><a href="{% url 'medioscolombia:canalestvlist' %}"><span>{% contarcanalestvcol %}</span>Televisión</a></li>
                <li><a href="{% url 'medioscolombia:radioslist' %}"><span>{% contarradioscol %}</span>Radio</a></li>
                <li><a href="{% url 'medioscolombia:gruposlist' %}"><span>{% contargruposcol %}</span>Grupos de Medios</a></li>
                <li><a href="{% url 'medioscolombia:propietarioslist' %}"><span>{% contarpropietarioscol %}</span>Propietarios</a></li>
                <li><a href="{% url 'medioscolombia:regulacioneslist' %}"><span>{% contarleyescol %}</span>Legislación</a></li>
                <li><a href="{% url 'medioscolombia:fuenteslist' %}"><span>{% contarfuentescol %}</span>Fuentes Utilizadas</a></li>
                  </ul>
                </li>
            <li class="item-li"><a href="{% url 'medioschile:analisislist' %}" class="item">Análisis</a></li>
            <li class="item-li"><a href="{% url 'medioschile:datos' %}" class="item">Datos</a></li>
            <li class="item-li"><a href="{% url 'medioschile:codigo' %}" class="item">Código</a></li>
            <li class="item-li"><a href="{% url 'medioschile:metodologia' %}" class="item">Metodología</a></li>
              </ul>
              <ul class="nav-s">
                <li class="item-li"><a href="#" class="item only-icon"><i class="icon icon-16 flaticon social facebook-1"></i> Facebook</a></li>
                <li class="item-li"><a href="https://twitter.com/poderomedia" class="item only-icon"><i class="icon icon-16 flaticon social twitter-1"></i> Twitter</a></li>
              </ul>
              <ul class="nav-s">
                <li class="item-li active"><a href="." class="item">ES</a></li>
                <li class="item-li"><a href="#" class="item">EN</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
  </header>
  
  {% block content %}{% endblock %}

 <section class="section-logos">
    <div class="row">
      <div class="col6">
        <h6>Investigación realizada por</h6>
        <ul>
          <li>
            <a href="http://www.poderopedia.org">
              <img src="{% static 'imgs/logos/poderopedia.png' %}" alt="Poderopedia" />
            </a>
          </li>
          <li>
            <a href="http://consejoderedaccion.org/">
              <img src="{% static 'imgs/logos/consejo.png' %}" alt="Consejo de redacción" />
            </a>
          </li>
        </ul>
      </div>
      <div class="col4">
        <h6>Proyecto financiado por</h6>
        <ul>
          <li>
            <a href="http://www.opensocietyfoundations.org/">
              <img src="{% static 'imgs/logos/open.png' %}" alt="Open Society" />
            </a>
          </li>
        </ul>
      </div>
      <div class="col6">
        <h6>Colaboración</h6>
        <ul>
          <li>
            <a href="http://www.uahurtado.cl/facultades-y-carreras/periodismo/">
              <img src="{% static 'imgs/logos/uah.png' %}" alt="Universidad Alberto Hurtado" />
            </a>
          </li>
          <li>
            <a href="http://www.javeriana.edu.co">
              <img src="{% static 'imgs/logos/javeriana.png' %}" alt="javeriana" />
            </a>
          </li>
        </ul>
      </div>
    </div>
  </section>

  <footer>
    <div class="row-module">
      <div class="row">
        <div class="col7">
          <h3 class="mapademedios">
            <a href="{% url 'medioschile:index' %}">Mapa de medios</a>
          </h3>
        </div>
        <div class="col5">
          <ul>
            <li><a href="#">¿Quieres tener un sitio web como este?</a></li>
            <li><a href="{% url 'medioschile:contacto' %}">Contacto</a></li>
            <li><a href="{% url 'medioschile:privacidad' %}">Privacidad y Legal</a></li>
          </ul>
        </div>
        <div class="col4">
          <ul>
            <li>
            <a href="https://twitter.com/poderomedia" class="with-icon"><i class="icon icon-16 flaticon social twitter-1"></i>Twitter</a>
            </li>
            <li>
            <a href="https://github.com/poderomedia/mapa-de-medios" class="with-icon"><i class="icon icon-16 flaticon social github-1"></i>Revisa el código en Github</a>
            </li>
            <li>
            <a href="http://www.facebook.com" class="with-icon"><i class="icon icon-16 flaticon social facebook-1"></i>Facebook</a>
            </li>
          </ul>
        </div>
      </div>
      <hr />
      <div class="row">
        <div class="col8 credits">
          <p>Un proyecto de Poderomedia {% now "Y" %}. El contenido de este sitio está disponible bajo licencia <a href="https://creativecommons.org/licenses/by/3.0/deed.es">Creative Commons Attribution 3.0.</a> Los datos están liberados bajo <a href="http://opendatacommons.org/licenses/odbl/1-0/">Open Database License (ODbL) v1.0.</a></p>
        </div>
        <div class="col7 prefix1">
          <form class="signup-newsletters">
            <div class="signup-form">
              <input class="input-footer" type="text" placeholder="Registrate para recibir novedades" />
            </div>
            <div class="signup-submit">
              <input type="submit" class="btn btn-primary" value="Enviar" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </footer>
  {% block js %}
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/application.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.dataTables.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/dataTables.tableTools.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/stacktable.js' %}"></script>
  {% endblock %}

<script>
$.fn.dataTable.TableTools.defaults.aButtons = [ "csv", "xls", "pdf", ];
$(document).ready(function() {
    $('#TablaLista').stacktable().DataTable( {
        order: [[1,'asc']],
        responsive: {
        details: true
    },
        dom: '<Tif<t>>',
        tableTools: {
            "sSwfPath": "../../static/swf/copy_csv_xls_pdf.swf"
        },
        aoColumnDefs: [
      { bSortable: false, aTargets: [ 0 ] }],
    } );
} );
</script>
</body>
</html>

templates/mediamapper/index.html
{% extends "mediamapper/base.html" %}
{% load medioschile_extras %}
{% load medioscolombia_extras %}
{% block content %}
<section class="section-featured row-module">
    <div class="row">
      <div class="col16">
      <form method="get" action=".">
        
    <div class="heading acenter">
          <h1>Descubre quién es quién en la Industria de medios de Chile y Colombia.</h1>
          <p>El Mapa de Medios es una base de datos de Medios de Comunicación de <a href=".">Chile</a> y <a href="{% url 'medioscolombia:index' %}">Colombia</a>, y quiénes son los propietarios de esos Medios. Incluye la mayor parte de los Medios Impresos, Digitales, Radiales y Televisivos de cada país un registro de cuáles son las leyes relativas a Medios y el ejercicio del Periodismo; y las fuentes de información consultadas para realizar esta investigación. Conoce el analisis, descarga los <a href="{% url 'medioschile:datos' %}">Datos</a>, usa la <a href="{% url 'api' %}">API</a>, revisa la <a href="{% url 'medioschile:metodologia' %}">Metodología</a> y reutiliza el <a href="{% url 'medioschile:codigo' %}">Código</a> de esta aplicación.</p>
        </div>
      </div>
      <div class="col12 prefix2">
      
     <form class="form-search" action="/search" method="GET">
            <div class="search-group">
              <div class="search-form">
                <i class="icon icon-16 flaticon stroke zoom-2"></i>
                <input type="text" name="q" placeholder="Buscar por el nombre del medio, propietario o grupo de medios" />
              </div>
              <div class="search-submit">
                <input type="submit" class="btn btn-m btn-primary" value="Buscar" />
              </div>
            </div>
            <div class="form-search-options">
              <label class="radio"><input type="radio" name="checkpais" value="cl" checked="checked"> Chile</label>
              <label class="radio"><input type="radio" name="checkpais" value="col"> Colombia</label>
              <p><i class="icon icon-16 flaticon solid question-2"></i> Selecciona el País donde quieres buscar.</p>
            </div>
    </form>
      </div>
    </div>
  </section>

  <section class="section-articles row-module">
    <div class="row">
      <div class="col16">
        <div class="heading acenter">
          <h3>Análisis</h3>
        </div>
      </div>

      <div id="slide-articles" class="carousel" data-ride="carousel" data-interval="false">
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <article class="col8">
            {% for articulo in articulos %}
            {% if articulo.posicion == "1" %}
              <a href="{% url 'medioschile:analisisdetail' articulo.pk %}">
                <h3>{{ articulo.titulo }}</h3>
                <figure>
                  <img src="{{ MEDIA_URL }}{{ articulo.imagen_destacada }}" />
                </figure>
                <span class="btn btn-s btn-default">
                  <i class="icon icon-16 flaticon stroke activity-1"></i> Leer
                </span>
              </a>
            {% endif %}
            {% endfor %}
            </article>
           
            <article class="col8">
            {% for articulo in articulos %}
            {% if articulo.posicion == "2" %}
              <a href="{% url 'medioschile:analisisdetail' articulo.pk %}">
                <h3>{{ articulo.titulo }}</h3>
                <figure>
                  <img src="{{ MEDIA_URL }}{{ articulo.imagen_destacada }}" />
                </figure>
                <span class="btn btn-s btn-default">
                  <i class="icon icon-16 flaticon stroke activity-1"></i> Leer
                </span>
              </a>
            {% endif %}
            {% endfor %}
            </article>
          </div>

          <div class="item">
            <article class="col8">
            {% for articulo in articulos %}
            {% if articulo.posicion == "3" %}
              <a href="{% url 'medioschile:analisisdetail' articulo.pk %}">
                <h3>{{ articulo.titulo }}</h3>
                <figure>
                  <img src="{{ MEDIA_URL }}{{ articulo.imagen_destacada }}" />
                </figure>
                <span class="btn btn-s btn-default">
                  <i class="icon icon-16 flaticon stroke activity-1"></i> Leer
                </span>
              </a>
            {% endif %}
            {% endfor %}
            </article>

            <article class="col8">
            {% for articulo in articulos %}
            {% if articulo.posicion == "4" %}
              <a href="{% url 'medioschile:analisisdetail' articulo.pk %}">
                <h3>{{ articulo.titulo }}</h3>
                <figure>
                  <img src="{{ MEDIA_URL }}{{ articulo.imagen_destacada }}" />
                </figure>
                <span class="btn btn-s btn-default">
                  <i class="icon icon-16 flaticon stroke activity-1"></i> Leer
                </span>
              </a>
            {% endif %}
            {% endfor %}
            </article>
          </div><!--/item-->
        </div>

        <a href="#slide-articles" class="ctrl prev" data-slide="prev">Previous</a>
        <a href="#slide-articles" class="ctrl next" data-slide="next">Next</a>

        <ol class="carousel-indicators">
          <li data-target="#slide-articles" data-slide-to="0" class="active">1</li>
          <li data-target="#slide-articles" data-slide-to="1">2</li>
        </ol>

      </div><!--/slide articles-->

    </div>
  </section>

  <section class="section-categories row-module"><a name="categorias"></a>
    <div class="row">
      <div class="col16">
        <div class="heading acenter">
          <h3>Descubre información por categorías</h3>
        </div>
      </div>
      <div class="col7">
        <h6><i class="icon icon-16 flaticon solid tag-1"></i> Medios de Chile</h6>
        <nav>
          <ul>
            <li><a href="{% url 'medioschile:digitaleslist' %}"><span>{% contardigitales %}</span>Medios Digitales</a></li>
            <li><a href="{% url 'medioschile:escritoslist' %}"><span>{% contarescritos %}</span>Impresos</a></li>
            <li><a href="{% url 'medioschile:canalestvlist' %}"><span>{% contarcanalestv %}</span>Televisión</a></li>
            <li><a href="{% url 'medioschile:radioslist' %}"><span>{% contarradios %}</span>Radio</a></li>
            <li><a href="{% url 'medioschile:gruposlist' %}"><span>{% contargrupos %}</span>Grupos de Medios</a></li>
            <li><a href="{% url 'medioschile:propietarioslist' %}"><span>{% contarpropietarios %}</span>Propietarios</a></li>
            <li><a href="{% url 'medioschile:regulacioneslist' %}"><span>{% contarleyes %}</span>Legislación</a></li>
            <li><a href="{% url 'medioschile:fuenteslist' %}"><span>{% contarfuentes %}</span>Fuentes Utilizadas</a></li>
          </ul>
        </nav>
      </div>
      <div class="col7 prefix2">
        <h6><i class="icon icon-16 flaticon solid tag-1"></i> Medios de Colombia</h6>
        <nav>
          <ul>
            <li><a href="{% url 'medioscolombia:digitaleslist' %}"><span>{% contardigitalescol %}</span>Medios Digitales</a></li>
            <li><a href="{% url 'medioscolombia:escritoslist' %}"><span>{% contarescritoscol %}</span>Impresos</a></li>
            <li><a href="{% url 'medioscolombia:canalestvlist' %}"><span>{% contarcanalestvcol %}</span>Televisión</a></li>
            <li><a href="{% url 'medioscolombia:radioslist' %}"><span>{% contarradioscol %}</span>Radio</a></li>
            <li><a href="{% url 'medioscolombia:gruposlist' %}"><span>{% contargruposcol %}</span>Grupos de Medios</a></li>
            <li><a href="{% url 'medioscolombia:propietarioslist' %}"><span>{% contarpropietarioscol %}</span>Propietarios</a></li>
            <li><a href="{% url 'medioscolombia:regulacioneslist' %}"><span>{% contarleyescol %}</span>Legislación</a></li>
            <li><a href="{% url 'medioscolombia:fuenteslist' %}"><span>{% contarfuentescol %}</span>Fuentes Utilizadas</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </section>

  <section class="row-module">
    <div class="row">
      <div class="col16">
        <div class="heading acenter">
          <h3>Conoce la metodología y <br/> reusa la información en tu proyecto</h3>
        </div>

        <div class="item-featured-list">
          <div class="item-featured">
            <a href="{% url 'medioschile:acercade' %}">
              <span>
                <i class="icon icon-32 flaticon solid open-book-1"></i>
              </span>
              <h6>Qué es el Mapa de Medios</h6>
              <p>El Mapa de Medios de Chile y Colombia es una base de datos sobre la industria de medios en estos países, sus dueños, actores que inciden en las políticas públicas y la legislación sobre los medios de comunicación.</p>
            </a>
          </div>
          <div class="item-featured">
            <a href="{% url 'medioschile:metodologia' %}">
              <span>
                <i class="icon icon-32 flaticon solid magic-wand-1"></i>
              </span>
              <h6>Cómo de hizo</h6>
              <p>Mapa de Medios de Chile y Colombia es el resultado de una investigación periodística, dos hackdays realizados en cada país donde se asistieron académicos, expertos, periodistas, diseñadores y programadores, quienes colaboraron en la construcción de una base de datos.</p>
            </a>
          </div>
          <div class="item-featured">
            <a href="{% url 'medioschile:datos' %}">
              <span>
                <i class="icon icon-32 flaticon solid download-1"></i>
              </span>
              <h6>Descarga los datos</h6>
              <p>Los datos recopilados en Mapa de Medios están disponibles para la comunidad (ciudadanos, estudiantes, investigadores, etc.) bajo una estructura de Open Data.</p>
            </a>
          </div>
          <div class="item-featured">
            <a href="{% url 'medioschile:codigo' %}">
              <span>
                <i class="icon icon-32 flaticon social github-1"></i>
              </span>
              <h6>Código abierto para tu proyecto</h6>
              <p>Este proyecto está construido sobre la aplicación de ingreso y publicación de datos de código abierto MediaMapper. Revisa cómo puedes crear tu propio proyecto sobre Medios.</p>
            </a>
          </div>
          <div class="item-featured">
            <a href="{% url 'api' %}">
              <span>
                <i class="icon icon-32 flaticon solid settings-2"></i>
              </span>
              <h6>Tenemos API</h6>
              <p>Si necesitas reutilizar nuestros datos en tiempo real, para tus aplicaciones o sitios web, tenemos API disponible. Puedes integrar Mapa de Medios a tus proyectos y te podemos ayudar si lo requieres.</p>
            </a>
          </div>
          <div class="item-featured">
            <a href="{% url 'medioschile:aporta' %}">
              <span>
                <i class="icon icon-32 flaticon solid mail-3"></i>
              </span>
              <h6>Agrega nueva información</h6>
              <p>Mapa de Medios permite a los usuarios aportar contenido a sus bases de datos a fin de incrementar la información y actualizaciones relativas a la propiedad de los medios de comunicación en Chile y Colombia.</p>
            </a>
          </div>
        </div>

      </div>
    </div>
  </section>

{% endblock %}