mediamapper/urls.py
from django.http import HttpResponse
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS admin
    url(r'^admin/',  include(admin.site.urls)), # admin site
    url(r'^select2/', include('select2.urls')), # select2 multiselect admin
    url(r'^home/', view=TemplateView.as_view(template_name="medioschile/index.html"), name='home'),
    url(r'^api/', view=TemplateView.as_view(template_name="api.html"), name='api'),
    url(r'^medioschile/', include('medioschile.urls', namespace='medioschile')), # medioschile
    url(r'^medioscolombia/', include('medioscolombia.urls', namespace='medioscolombia')), # medioscolombia
    url(r'^redactor/', include('redactor.urls')), # redactor editor
    url(r'^search/', include('haystack.urls')),

)	+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medioschile/urls.py
from . import views
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from rest_framework import routers
from medioschile import serializers

router = routers.DefaultRouter()
router.register(r'propietarios', views.PropietarioViewSet)
router.register(r'sociedades', views.SociedadViewSet)
router.register(r'tiposociedades', views.TipoSociedadViewSet)
router.register(r'grupos', views.GrupoViewSet)
router.register(r'paises', views.PaisSociedadViewSet)
router.register(r'fuentes', views.FuenteViewSet)
router.register(r'escritos', views.EscritoViewSet)
router.register(r'canaltvs', views.CanalTVViewSet)
router.register(r'generoradios', views.GeneroRadioViewSet)
router.register(r'generoescritos', views.GeneroEscritoViewSet)
router.register(r'generocanaltvs', views.GeneroCanalTVViewSet)
router.register(r'generomediodigitales', views.GeneroMedioDigitalViewSet)
router.register(r'radios', views.RadioViewSet)
router.register(r'mediodigitales', views.MedioDigitalViewSet)
router.register(r'ejecutivos', views.EjecutivoViewSet)
router.register(r'empresarios', views.EmpresarioViewSet)
router.register(r'articulos', views.ArticuloViewSet)
router.register(r'autores', views.AutorViewSet)

urlpatterns = [
	url(r'^index/$', 'medioschile.views.index', name='index'),
    url(r'^acercade/$', 'medioschile.views.acercade', name='acercade'),
	url(r'^consultadirecta/$', 'medioschile.views.consultadirecta', name='consultadirecta'),
    url(r'^metodologia/$', 'medioschile.views.metodologia', name='metodologia'),
    url(r'^privacidad/$', 'medioschile.views.privacidad', name='privacidad'),
    url(r'^datos/$', 'medioschile.views.datos', name='datos'),
    url(r'^codigo/$', 'medioschile.views.codigo', name='codigo'),
    url(r'^contacto/$', 'medioschile.views.contacto', name='contacto'),
    url(r'^aporta/$', 'medioschile.views.aporta', name='aporta'),
    url(r'^analisiscl/$', 'medioschile.views.analisiscl', name='analisiscl'),
    url(r'^analisiscol/$', 'medioschile.views.analisiscol', name='analisiscol'),
    url(r'^fuente/$', views.FuenteList.as_view(), name='fuenteslist'),
    url(r'^analisis/$', views.AnalisisList.as_view(), name='analisislist'),
    url(r'^analisis/(?P<pk>\d+)/$', views.AnalisisDetail.as_view(), name='analisisdetail'),
    url(r'^regulacion/$', views.RegulacionList.as_view(), name='regulacioneslist'),
    url(r'^regulacion/(?P<pk>\d+)/$', views.RegulacionDetail.as_view(), name='regulaciondetail'),
    url(r'^grupo/(?P<pk>\d+)/$', views.GrupoDetail.as_view(), name='grupodetail'),
    url(r'^grupo/$', views.GrupoList.as_view(), name='gruposlist'),
    url(r'^propietario/$', views.PropietarioList.as_view(), name='propietarioslist'),
    url(r'^propietario/(?P<pk>\d+)/$', views.PropietarioDetail.as_view(), name='propietariodetail'),
    url(r'^escritolist/$', views.EscritoList.as_view(), name='escritoslist'),
    url(r'^escritolist/(?P<pk>\d+)/$', views.EscritoDetail.as_view(), name='escritodetail'),
    url(r'^canaltvlist/$', views.CanalTVList.as_view(), name='canalestvlist'),
    url(r'^canaltvlist/(?P<pk>\d+)/$', views.CanalTVDetail.as_view(), name='canaltvdetail'),
    url(r'^radiolist/$', views.RadioList.as_view(), name='radioslist'),
    url(r'^radiolist/(?P<pk>\d+)/$', views.RadioDetail.as_view(), name='radiodetail'),
    url(r'^mediodigitallist/$', views.MedioDigitalList.as_view(), name='digitaleslist'),
    url(r'^mediodigitallist/(?P<pk>\d+)/$', views.MedioDigitalDetail.as_view(), name='digitaldetail'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

medioscolombia/urls.py
from . import views
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from medioscolombia.views import *
from rest_framework import routers
from medioscolombia import serializers

router = routers.DefaultRouter()
router.register(r'propietarios', views.PropietarioViewSet)
router.register(r'sociedades', views.SociedadViewSet)
router.register(r'tiposociedades', views.TipoSociedadViewSet)
router.register(r'grupos', views.GrupoViewSet)
router.register(r'paises', views.PaisSociedadViewSet)
router.register(r'fuentes', views.FuenteViewSet)
router.register(r'escritos', views.EscritoViewSet)
router.register(r'canaltvs', views.CanalTVViewSet)
router.register(r'radios', views.RadioViewSet)
router.register(r'generoradios', views.GeneroRadioViewSet)
router.register(r'generoescritos', views.GeneroEscritoViewSet)
router.register(r'generocanaltvs', views.GeneroCanalTVViewSet)
router.register(r'generomediodigitales', views.GeneroMedioDigitalViewSet)
router.register(r'mediodigitales', views.MedioDigitalViewSet)
router.register(r'ejecutivos', views.EjecutivoViewSet)
router.register(r'empresarios', views.EmpresarioViewSet)
router.register(r'autores', views.AutorViewSet)

urlpatterns = [
	url(r'^index/$', 'medioscolombia.views.index', name='index'),
    url(r'^contacto/$', 'medioscolombia.views.contacto', name='contacto'),
    url(r'^aporta/$', 'medioscolombia.views.aporta', name='aporta'),
    url(r'^fuente/$', views.FuenteList.as_view(), name='fuenteslist'),
    url(r'^regulacion/$', views.RegulacionList.as_view(), name='regulacioneslist'),
    url(r'^regulacion/(?P<pk>\d+)/$', views.RegulacionDetail.as_view(), name='regulaciondetail'),
    url(r'^grupo/(?P<pk>\d+)/$', views.GrupoDetail.as_view(), name='grupodetail'),
    url(r'^grupo/$', views.GrupoList.as_view(), name='gruposlist'),
    url(r'^propietario/$', views.PropietarioList.as_view(), name='propietarioslist'),
    url(r'^propietario/(?P<pk>\d+)/$', views.PropietarioDetail.as_view(), name='propietariodetail'),
    url(r'^escritolist/$', views.EscritoList.as_view(), name='escritoslist'),
    url(r'^escritolist/(?P<pk>\d+)/$', views.EscritoDetail.as_view(), name='escritodetail'),
    url(r'^canaltvlist/$', views.CanalTVList.as_view(), name='canalestvlist'),
    url(r'^canaltvlist/(?P<pk>\d+)/$', views.CanalTVDetail.as_view(), name='canaltvdetail'),
    url(r'^radiolist/$', views.RadioList.as_view(), name='radioslist'),
    url(r'^radiolist/(?P<pk>\d+)/$', views.RadioDetail.as_view(), name='radiodetail'),
    url(r'^mediodigitallist/$', views.MedioDigitalList.as_view(), name='digitaleslist'),
    url(r'^mediodigitallist/(?P<pk>\d+)/$', views.MedioDigitalDetail.as_view(), name='digitaldetail'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

medioscolombia/views.py
from django.db import models
from django.shortcuts import render,render_to_response
from django.http import Http404,HttpResponse,HttpResponseRedirect
from django.views.generic import ListView
from django.views.generic import DetailView
from medioscolombia.models import Ejecutivo,Empresario,GeneroEscrito,Region,Ciudad,Sector,Periodicidad,Propietario,TipoSociedad,PaisSociedad,Sociedad,Grupo,Escrito,GeneroRadio,Radio,GeneroCanalTV,CanalTV,GeneroMedioDigital,MedioDigital,Autor,Fuente,TipoDocumento,Regulacion,CargoEjecutivo,Cargo
from medioschile.models import Articulo
from rest_framework import viewsets
from medioscolombia.serializers import *

def index(request):
	articulos = Articulo.objects.filter(destacado = 1)
	return render(request, 'medioscolombia/index.html', {"articulos":articulos})

def consultadirecta(request):
	return render(request, 'medioscolombia/consultadirecta.html')

def metodologia(request):
	return render(request, 'medioscolombia/metodologia.html')

def datos(request):
	return render(request, 'medioscolombia/datos.html')

def codigo(request):
	return render(request, 'medioscolombia/codigo.html')

def analisis(request):
	return render(request, 'medioscolombia/analisis.html')

def acercade(request):
	return render(request, 'medioscolombia/acercade.html')

def contacto(request):
	return render(request, 'medioscolombia/contacto.html')

def aporta(request):
	return render(request, 'medioscolombia/aporta.html')

def privacidad(request):
	return render(request, 'medioscolombia/privacidad.html')

class EscritoList(ListView):
	model = Escrito
	context_object_name = 'escrito_list'
	template_name = 'medioscolombia/escrito_list.html'

class EscritoDetail(DetailView):
	model = Escrito
	context_object_name = 'escrito_detail'
	template_name = 'medioscolombia/escrito_detail.html'

class CanalTVList(ListView):
	model = CanalTV
	context_object_name = 'canaltv_list'
	template_name = 'medioscolombia/canaltv_list.html'

class CanalTVDetail(DetailView):
	model = CanalTV
	context_object_name = 'canaltv_detail'
	template_name = 'medioscolombia/canaltv_detail.html'

class RadioList(ListView):
	model = Radio
	context_object_name = 'radio_list'
	template_name = 'medioscolombia/radio_list.html'

class RadioDetail(DetailView):
	model = Radio
	context_object_name = 'radio_detail'
	template_name = 'medioscolombia/radio_detail.html'

class MedioDigitalList(ListView):
	model = MedioDigital
	context_object_name = 'mediodigital_list'
	template_name = 'medioscolombia/mediodigital_list.html'

class MedioDigitalDetail(DetailView):
	model = MedioDigital
	context_object_name = 'mediodigital_detail'
	template_name = 'medioscolombia/mediodigital_detail.html'

class PropietarioDetail(DetailView):
	model = Propietario
	context_object_name = 'propietario_detail'
	template_name = 'medioscolombia/propietario_detail.html'

class PropietarioList(ListView):
	model = Propietario
	context_object_name = 'propietario_list'
	template_name = 'medioscolombia/propietario_list.html'

class GrupoDetail(DetailView):
	model = Grupo
	context_object_name = 'grupo_detail'
	template_name = 'medioscolombia/grupo_detail.html'

class GrupoList(ListView):
	model = Grupo
	context_object_name = 'grupo_list'
	template_name = 'medioscolombia/grupo_list.html'

class RegulacionDetail(DetailView):
	model = Regulacion
	context_object_name = 'regulacion_detail'
	template_name = 'medioscolombia/regulacion_detail.html'

class RegulacionList(ListView):
	model = Regulacion
	context_object_name = 'regulacion_list'
	template_name = 'medioscolombia/regulacion_list.html'

class FuenteList(ListView):
	model = Fuente
	context_object_name = 'fuente_list'
	template_name = 'medioscolombia/fuente_list.html'

class PropietarioViewSet(viewsets.ModelViewSet):
    queryset = Propietario.objects.all()
    serializer_class = PropietarioSerializer

class TipoSociedadViewSet(viewsets.ModelViewSet):
	queryset = TipoSociedad.objects.all()
	serializer_class = TipoSociedadSerializer

class SociedadViewSet(viewsets.ModelViewSet):
    queryset = Sociedad.objects.all()
    serializer_class = SociedadSerializer

class GrupoViewSet(viewsets.ModelViewSet):
    queryset = Grupo.objects.all()
    serializer_class = GrupoSerializer

class PaisSociedadViewSet(viewsets.ModelViewSet):
    queryset = PaisSociedad.objects.all()
    serializer_class = PaisSociedadSerializer

class RadioViewSet(viewsets.ModelViewSet):
    queryset = Radio.objects.all()
    serializer_class = RadioSerializer

class EscritoViewSet(viewsets.ModelViewSet):
    queryset = Escrito.objects.all()
    serializer_class = EscritoSerializer

class CanalTVViewSet(viewsets.ModelViewSet):
    queryset = CanalTV.objects.all()
    serializer_class = CanalTVSerializer

class MedioDigitalViewSet(viewsets.ModelViewSet):
    queryset = MedioDigital.objects.all()
    serializer_class = MedioDigitalSerializer

class GeneroRadioViewSet(viewsets.ModelViewSet):
    queryset = GeneroRadio.objects.all()
    serializer_class = GeneroRadioSerializer

class GeneroCanalTVViewSet(viewsets.ModelViewSet):
    queryset = GeneroCanalTV.objects.all()
    serializer_class = GeneroCanalTVSerializer

class GeneroEscritoViewSet(viewsets.ModelViewSet):
    queryset = GeneroEscrito.objects.all()
    serializer_class = GeneroEscritoSerializer

class GeneroMedioDigitalViewSet(viewsets.ModelViewSet):
    queryset = GeneroMedioDigital.objects.all()
    serializer_class = GeneroMedioDigitalSerializer

class GeneroRadioViewSet(viewsets.ModelViewSet):
    queryset = GeneroRadio.objects.all()
    serializer_class = GeneroRadioSerializer

class FuenteViewSet(viewsets.ModelViewSet):
    queryset = Fuente.objects.all()
    serializer_class = FuenteSerializer

class EmpresarioViewSet(viewsets.ModelViewSet):
    queryset = Empresario.objects.all()
    serializer_class = EmpresarioSerializer

class EjecutivoViewSet(viewsets.ModelViewSet):
    queryset = Ejecutivo.objects.all()
    serializer_class = EjecutivoSerializer

class AutorViewSet(viewsets.ModelViewSet):
    queryset = Autor.objects.all()
    serializer_class = AutorSerializer

templates/medioscolombia/base.html
{% load staticfiles %}
{% load medioschile_extras %}
{% load medioscolombia_extras %}
<html lang="es">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
<link rel="stylesheet" type="text/css" href="{% static 'css/mediamapper.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/application.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/jquery.dataTables.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/dataTables.tableTools.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'css/stacktable.css' %}" />
<!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<title>{% block title %}Mapa de Medios{% endblock %}</title>
</head>

<body>

<header>
      <div class="row">
        <div class="col16">
          <h2 class="mapademedios">
            <a href="{% url 'medioscolombia:index' %}">Mapa de medios</a>
          </h2>
          <a href="#" class="main-nav-mobile collapsed" data-toggle="collapse" data-target="#wrap-mobile-navigation">
            <i class="icon icon-16 flaticon stroke menu-3"></i> Mostrar menu
          </a>
          <div id="wrap-mobile-navigation" class="wrap-mobile-navigation collapse">
            <nav>
              <ul>
                <li class="item-li active"><a href="{% url 'medioschile:acercade' %}" class="item">Acerca de</a></li>
                <li class="item-li dropdown-nav with-count dropdown">
                  <a href="#" data-toggle="dropdown" class="dropdown-toggle item">Medios Chile <span class="arrow"></span></a>
                  <ul class="dropdown-menu">
                <li><a href="{% url 'medioschile:digitaleslist' %}"><span>{% contardigitales %}</span>Medios Digitales</a></li>
                <li><a href="{% url 'medioschile:escritoslist' %}"><span>{% contarescritos %}</span>Impresos</a></li>
                <li><a href="{% url 'medioschile:canalestvlist' %}"><span>{% contarcanalestv %}</span>Televisión</a></li>
                <li><a href="{% url 'medioschile:radioslist' %}"><span>{% contarradios %}</span>Radio</a></li>
                <li><a href="{% url 'medioschile:gruposlist' %}"><span>{% contargrupos %}</span>Grupos de Medios</a></li>
                <li><a href="{% url 'medioschile:propietarioslist' %}"><span>{% contarpropietarios %}</span>Propietarios</a></li>
                <li><a href="{% url 'medioschile:regulacioneslist' %}"><span>{% contarleyes %}</span>Legislación</a></li>
                <li><a href="{% url 'medioschile:fuenteslist' %}"><span>{% contarfuentes %}</span>Fuentes Utilizadas</a></li>
                  </ul>
                </li>
                <li class="item-li dropdown-nav with-count dropdown">
                  <a href="#" data-toggle="dropdown" class="dropdown-toggle item">Medios Colombia <span class="arrow"></span></a>
                  <ul class="dropdown-menu">
                <li><a href="{% url 'medioscolombia:digitaleslist' %}"><span>{% contardigitalescol %}</span>Medios Digitales</a></li>
                <li><a href="{% url 'medioscolombia:escritoslist' %}"><span>{% contarescritoscol %}</span>Impresos</a></li>
                <li><a href="{% url 'medioscolombia:canalestvlist' %}"><span>{% contarcanalestvcol %}</span>Televisión</a></li>
                <li><a href="{% url 'medioscolombia:radioslist' %}"><span>{% contarradioscol %}</span>Radio</a></li>
                <li><a href="{% url 'medioscolombia:gruposlist' %}"><span>{% contargruposcol %}</span>Grupos de Medios</a></li>
                <li><a href="{% url 'medioscolombia:propietarioslist' %}"><span>{% contarpropietarioscol %}</span>Propietarios</a></li>
                <li><a href="{% url 'medioscolombia:regulacioneslist' %}"><span>{% contarleyescol %}</span>Legislación</a></li>
                <li><a href="{% url 'medioscolombia:fuenteslist' %}"><span>{% contarfuentescol %}</span>Fuentes Utilizadas</a></li>
                  </ul>
                </li>
            <li class="item-li"><a href="{% url 'medioschile:analisislist' %}" class="item">Análisis</a></li>
            <li class="item-li"><a href="{% url 'medioschile:datos' %}" class="item">Datos</a></li>
            <li class="item-li"><a href="{% url 'medioschile:codigo' %}" class="item">Código</a></li>
            <li class="item-li"><a href="{% url 'medioschile:metodologia' %}" class="item">Metodología</a></li>
              </ul>
              <ul class="nav-s">
                <li class="item-li"><a href="#" class="item only-icon"><i class="icon icon-16 flaticon social facebook-1"></i> Facebook</a></li>
                <li class="item-li"><a href="https://twitter.com/poderomedia" class="item only-icon"><i class="icon icon-16 flaticon social twitter-1"></i> Twitter</a></li>
              </ul>
              <ul class="nav-s">
                <li class="item-li active"><a href="." class="item">ES</a></li>
                <li class="item-li"><a href="#" class="item">EN</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
  </header>
  
  {% block content %}{% endblock %}

 <section class="section-logos">
    <div class="row">
      <div class="col6">
        <h6>Investigación realizada por</h6>
        <ul>
          <li>
            <a href="http://www.poderopedia.org">
              <img src="{% static 'imgs/logos/poderopedia.png' %}" alt="Poderopedia" />
            </a>
          </li>
          <li>
            <a href="http://consejoderedaccion.org/">
              <img src="{% static 'imgs/logos/consejo.png' %}" alt="Consejo de redacción" />
            </a>
          </li>
        </ul>
      </div>
      <div class="col4">
        <h6>Proyecto financiado por</h6>
        <ul>
          <li>
            <a href="http://www.opensocietyfoundations.org/">
              <img src="{% static 'imgs/logos/open.png' %}" alt="Open Society" />
            </a>
          </li>
        </ul>
      </div>
      <div class="col6">
        <h6>Colaboración</h6>
        <ul>
          <li>
            <a href="http://www.uahurtado.cl/facultades-y-carreras/periodismo/">
              <img src="{% static 'imgs/logos/uah.png' %}" alt="Universidad Alberto Hurtado" />
            </a>
          </li>
          <li>
            <a href="http://www.javeriana.edu.co">
              <img src="{% static 'imgs/logos/javeriana.png' %}" alt="javeriana" />
            </a>
          </li>
        </ul>
      </div>
    </div>
  </section>

  <footer>
    <div class="row-module">
      <div class="row">
        <div class="col7">
          <h3 class="mapademedios">
            <a href="{% url 'medioscolombia:index' %}">Mapa de medios</a>
          </h3>
        </div>
        <div class="col5">
          <ul>
            <li><a href="#">¿Quieres tener un sitio web como este?</a></li>
            <li><a href="{% url 'medioscolombia:contacto' %}">Contacto</a></li>
            <li><a href="{% url 'medioschile:privacidad' %}">Privacidad y Legal</a></li>
          </ul>
        </div>
        <div class="col4">
          <ul>
            <li><a href="https://twitter.com/poderomedia" class="with-icon"><i class="icon icon-16 flaticon social twitter-1"></i> Twitter</a></li>
            <li><a href="https://github.com/poderomedia/mapa-de-medios" class="with-icon"><i class="icon icon-16 flaticon social github-1"></i> Revisa el código en Github</a></li>
            <li><a href="#" class="with-icon"><i class="icon icon-16 flaticon social facebook-1"></i> Facebook</a></li>
          </ul>
        </div>
      </div>
      <hr />
      <div class="row">
        <div class="col8 credits">
          <p>Un proyecto de Poderomedia {% now "Y" %}. El contenido de este sitio está disponible bajo licencia <a href="https://creativecommons.org/licenses/by/3.0/deed.es">Creative Commons Attribution 3.0.</a> Los datos están liberados bajo <a href="http://opendatacommons.org/licenses/odbl/1-0/">Open Database License (ODbL) v1.0.</a></p>
        </div>
        <div class="col7 prefix1">
          <form class="signup-newsletters">
            <div class="signup-form">
              <input type="text" placeholder="Registrate para recibir novedades" />
            </div>
            <div class="signup-submit">
              <input type="submit" class="btn btn-primary" value="Enviar" />
            </div>
          </form>
        </div>
      </div>
    </div>
  </footer>
  {% block js %}
  <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/application.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/jquery.dataTables.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/dataTables.tableTools.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/stacktable.js' %}"></script>
  {% endblock %}

<script>
$.fn.dataTable.TableTools.defaults.aButtons = [ "csv", "xls", "pdf", ];
$(document).ready(function() {
    $('#TablaLista').stacktable().DataTable( {
        order: [[1,'asc']],
        responsive: {
        details: true
    },
        dom: '<Tif<t>>',
        tableTools: {
            "sSwfPath": "../../static/swf/copy_csv_xls_pdf.swf"
        },
        aoColumnDefs: [
      { bSortable: false, aTargets: [ 0 ] }],
    } );
} );
</script>
</body>
</html>

templates/medioscolombia/canaltv_list.html
{% extends "medioscolombia/base.html" %}
{% block content %}
<section class="section-title row-module row-module-s-bottom">
    <div class="row">
      <div class="col16">
        <div class="heading acenter">
          <h1>Canales de Televisión de Colombia</h1>
          <h2>Tenemos registrados {{ canaltv_list.count }} Canales de Televisión de Colombia. Conoce la <a href="/medioscolombia/metodologia">metodología</a> usada para esta investigación y descarga los <a href="/medioscolombia/datos">datos.</a></h2>
        </div>
      </div>
    </div>
</section>

<section class="row-module row-module-s-top">
    <div class="row">
      <div class="col16">

        <!-- <div class="pager-info">
          <span class="right">Descargar: <a href="#">CSV</a>, <a href="#">XLS</a>, <a href="#">JSON</a></span>
        </div> -->

<table id="TablaLista" class="display" width="100%" cellspacing="0">

    <thead>
    <tr>
    <th width="5%" align="left">Medio</th>
    <th width="15%" align="left"></th>
    <th width="20%" align="left">Propietario</th>
    <th width="15%" align="left">Señal</th>
    <th width="15%" align="left">Cobertura</th>
    <th width="15%" align="left">Grupo</th>
    <th width="15%" align="left">Web</th>
    </tr>
    </thead>

    <tbody>
    {% for canaltv in canaltv_list %}
        <tr>
        <td><img class="img-circle" src="{{ MEDIA_URL }}{{ canaltv.logo }}" width="50px"/></td>
        <td><a href="{{ canaltv.pk }}">{{ canaltv.medio }}</a></td>
        <td>{% for propietario in canaltv.propietario.all %}<a href="/medioscolombia/propietario/{{ propietario.id }}">{{ propietario }}</a>{% empty %}No hay información{% endfor %}</td>
        <td>{{ canaltv.tipo | default:"No hay información" }}</td>
        <td>{{ canaltv.cobertura | default:"No hay información" }}</td>
        <td>{{ canaltv.grupo | default:"No hay información" }}</td> 
        <td>{% if canaltv.sitioweb %}<a href="{{ canaltv.sitioweb }}">{{ canaltv.sitioweb | truncatechars:20 }}</a>{% else %}No hay información{% endif %}</td> 
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5">
            </td>
        </tr>
    </tfoot>
    </table>
      </div>
    </div>
</section>

{% endblock %}