mediamapper/urls.py
from django.http import HttpResponse
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS admin
    url(r'^admin/',  include(admin.site.urls)), # admin site
    url(r'^select2/', include('select2.urls')), # select2 multiselect admin
    url(r'^home/', view=TemplateView.as_view(template_name="medioschile/index.html"), name='home'),
    url(r'^api/', view=TemplateView.as_view(template_name="api.html"), name='api'),
    url(r'^medioschile/', include('medioschile.urls', namespace='medioschile')), # medioschile
    url(r'^medioscolombia/', include('medioscolombia.urls', namespace='medioscolombia')), # medioscolombia
    url(r'^redactor/', include('redactor.urls')), # redactor editor
    url(r'^search/', include('haystack.urls')),

)	+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medioschile/urls.py
from . import views
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from rest_framework import routers
from medioschile import serializers

router = routers.DefaultRouter()
router.register(r'propietarios', views.PropietarioViewSet)
router.register(r'sociedades', views.SociedadViewSet)
router.register(r'tiposociedades', views.TipoSociedadViewSet)
router.register(r'grupos', views.GrupoViewSet)
router.register(r'paises', views.PaisSociedadViewSet)
router.register(r'fuentes', views.FuenteViewSet)
router.register(r'escritos', views.EscritoViewSet)
router.register(r'canaltvs', views.CanalTVViewSet)
router.register(r'generoradios', views.GeneroRadioViewSet)
router.register(r'generoescritos', views.GeneroEscritoViewSet)
router.register(r'generocanaltvs', views.GeneroCanalTVViewSet)
router.register(r'generomediodigitales', views.GeneroMedioDigitalViewSet)
router.register(r'radios', views.RadioViewSet)
router.register(r'mediodigitales', views.MedioDigitalViewSet)
router.register(r'ejecutivos', views.EjecutivoViewSet)
router.register(r'empresarios', views.EmpresarioViewSet)
router.register(r'articulos', views.ArticuloViewSet)
router.register(r'autores', views.AutorViewSet)

urlpatterns = [
	url(r'^index/$', 'medioschile.views.index', name='index'),
    url(r'^acercade/$', 'medioschile.views.acercade', name='acercade'),
	url(r'^consultadirecta/$', 'medioschile.views.consultadirecta', name='consultadirecta'),
    url(r'^metodologia/$', 'medioschile.views.metodologia', name='metodologia'),
    url(r'^privacidad/$', 'medioschile.views.privacidad', name='privacidad'),
    url(r'^datos/$', 'medioschile.views.datos', name='datos'),
    url(r'^codigo/$', 'medioschile.views.codigo', name='codigo'),
    url(r'^contacto/$', 'medioschile.views.contacto', name='contacto'),
    url(r'^aporta/$', 'medioschile.views.aporta', name='aporta'),
    url(r'^analisiscl/$', 'medioschile.views.analisiscl', name='analisiscl'),
    url(r'^analisiscol/$', 'medioschile.views.analisiscol', name='analisiscol'),
    url(r'^fuente/$', views.FuenteList.as_view(), name='fuenteslist'),
    url(r'^analisis/$', views.AnalisisList.as_view(), name='analisislist'),
    url(r'^analisis/(?P<pk>\d+)/$', views.AnalisisDetail.as_view(), name='analisisdetail'),
    url(r'^regulacion/$', views.RegulacionList.as_view(), name='regulacioneslist'),
    url(r'^regulacion/(?P<pk>\d+)/$', views.RegulacionDetail.as_view(), name='regulaciondetail'),
    url(r'^grupo/(?P<pk>\d+)/$', views.GrupoDetail.as_view(), name='grupodetail'),
    url(r'^grupo/$', views.GrupoList.as_view(), name='gruposlist'),
    url(r'^propietario/$', views.PropietarioList.as_view(), name='propietarioslist'),
    url(r'^propietario/(?P<pk>\d+)/$', views.PropietarioDetail.as_view(), name='propietariodetail'),
    url(r'^escritolist/$', views.EscritoList.as_view(), name='escritoslist'),
    url(r'^escritolist/(?P<pk>\d+)/$', views.EscritoDetail.as_view(), name='escritodetail'),
    url(r'^canaltvlist/$', views.CanalTVList.as_view(), name='canalestvlist'),
    url(r'^canaltvlist/(?P<pk>\d+)/$', views.CanalTVDetail.as_view(), name='canaltvdetail'),
    url(r'^radiolist/$', views.RadioList.as_view(), name='radioslist'),
    url(r'^radiolist/(?P<pk>\d+)/$', views.RadioDetail.as_view(), name='radiodetail'),
    url(r'^mediodigitallist/$', views.MedioDigitalList.as_view(), name='digitaleslist'),
    url(r'^mediodigitallist/(?P<pk>\d+)/$', views.MedioDigitalDetail.as_view(), name='digitaldetail'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

medioschile/forms.py
from django import forms

class ContactoForm(forms.Form):
	su_nombre = forms.CharField(label='Nombre', max_length=200)
	asunto = forms.CharField(label='Asunto', max_length=100)
	mensaje = forms.CharField(label='Mensaje', widget=forms.Textarea)
	email = forms.EmailField()
	cc_myself = forms.BooleanField(label='Nombre', required=False)

medioschile/views.py
from django.db import models
from django.shortcuts import render,render_to_response
from django.http import Http404,HttpResponse,HttpResponseRedirect
from django.views.generic import ListView
from django.views.generic import DetailView
from medioschile.models import *
from rest_framework import viewsets
from medioschile.serializers import *
from .forms import ContactoForm
from django.core.mail import send_mail

def index(request):
	articulos = Articulo.objects.filter(destacado = 1)
	return render(request, 'medioschile/index.html', {"articulos":articulos})

def consultadirecta(request):
	return render(request, 'medioschile/consultadirecta.html')

def metodologia(request):
	return render(request, 'medioschile/metodologia.html')

def datos(request):
	return render(request, 'medioschile/datos.html')

def codigo(request):
	return render(request, 'medioschile/codigo.html')

def analisis(request):
	return render(request, 'medioschile/analisis.html')

def acercade(request):
	return render(request, 'medioschile/acercade.html')

def contacto(request):
	return render(request, 'medioschile/contacto.html')

def aporta(request):
	return render(request, 'medioschile/aporta.html')

def privacidad(request):
	return render(request, 'medioschile/privacidad.html')

class EscritoList(ListView):
	model = Escrito
	context_object_name = 'escrito_list'
	template_name = 'medioschile/escrito_list.html'

class EscritoDetail(DetailView):
	model = Escrito
	context_object_name = 'escrito_detail'
	template_name = 'medioschile/escrito_detail.html'

class CanalTVList(ListView):
	model = CanalTV
	context_object_name = 'canaltv_list'
	template_name = 'medioschile/canaltv_list.html'

class CanalTVDetail(DetailView):
	model = CanalTV
	context_object_name = 'canaltv_detail'
	template_name = 'medioschile/canaltv_detail.html'

class RadioList(ListView):
	model = Radio
	context_object_name = 'radio_list'
	template_name = 'medioschile/radio_list.html'

class RadioDetail(DetailView):
	model = Radio
	context_object_name = 'radio_detail'
	template_name = 'medioschile/radio_detail.html'

class MedioDigitalList(ListView):
	model = MedioDigital
	context_object_name = 'mediodigital_list'
	template_name = 'medioschile/mediodigital_list.html'

class MedioDigitalDetail(DetailView):
	model = MedioDigital
	context_object_name = 'mediodigital_detail'
	template_name = 'medioschile/mediodigital_detail.html'

class PropietarioDetail(DetailView):
	model = Propietario
	context_object_name = 'propietario_detail'
	template_name = 'medioschile/propietario_detail.html'

class PropietarioList(ListView):
	model = Propietario
	context_object_name = 'propietario_list'
	template_name = 'medioschile/propietario_list.html'

class GrupoDetail(DetailView):
	model = Grupo
	context_object_name = 'grupo_detail'
	template_name = 'medioschile/grupo_detail.html'

class GrupoList(ListView):
	model = Grupo
	context_object_name = 'grupo_list'
	template_name = 'medioschile/grupo_list.html'

class RegulacionDetail(DetailView):
	model = Regulacion
	context_object_name = 'regulacion_detail'
	template_name = 'medioschile/regulacion_detail.html'

class RegulacionList(ListView):
	model = Regulacion
	context_object_name = 'regulacion_list'
	template_name = 'medioschile/regulacion_list.html'

class AnalisisDetail(DetailView):
	model = Articulo
	context_object_name = 'analisis_detail'
	template_name = 'medioschile/analisis_detail.html'

class AnalisisList(ListView):
	model = Articulo
	context_object_name = 'analisis_list'
	template_name = 'medioschile/analisis_list.html'

class FuenteList(ListView):
	model = Fuente
	context_object_name = 'fuente_list'
	template_name = 'medioschile/fuente_list.html'

def analisiscl(request):
	analisiscl = Articulo.objects.filter(pais = 1)
	return render(request, 'medioschile/analisis_listcl.html', {"analisiscl":analisiscl})

def analisiscol(request):
	analisiscol = Articulo.objects.filter(pais = 6)
	return render(request, 'medioschile/analisis_listcol.html', {"analisiscol":analisiscol})

def etiquetas(request):
    etiquetas = Etiqueta.objects.all()
    return render(request, 'medioschile/analisis_list.html', {"etiquetas":etiquetas})

class PropietarioViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Propietario.objects.all()
    serializer_class = PropietarioSerializer

class TipoSociedadViewSet(viewsets.ModelViewSet):
	queryset = TipoSociedad.objects.all()
	serializer_class = TipoSociedadSerializer

class SociedadViewSet(viewsets.ModelViewSet):
    queryset = Sociedad.objects.all()
    serializer_class = SociedadSerializer

class GrupoViewSet(viewsets.ModelViewSet):
    queryset = Grupo.objects.all()
    serializer_class = GrupoSerializer

class PaisSociedadViewSet(viewsets.ModelViewSet):
    queryset = PaisSociedad.objects.all()
    serializer_class = PaisSociedadSerializer

class RadioViewSet(viewsets.ModelViewSet):
    queryset = Radio.objects.all()
    serializer_class = RadioSerializer

class EscritoViewSet(viewsets.ModelViewSet):
    queryset = Escrito.objects.all()
    serializer_class = EscritoSerializer

class CanalTVViewSet(viewsets.ModelViewSet):
    queryset = CanalTV.objects.all()
    serializer_class = CanalTVSerializer

class MedioDigitalViewSet(viewsets.ModelViewSet):
    queryset = MedioDigital.objects.all()
    serializer_class = MedioDigitalSerializer

class GeneroRadioViewSet(viewsets.ModelViewSet):
    queryset = GeneroRadio.objects.all()
    serializer_class = GeneroRadioSerializer

class GeneroCanalTVViewSet(viewsets.ModelViewSet):
    queryset = GeneroCanalTV.objects.all()
    serializer_class = GeneroCanalTVSerializer

class GeneroEscritoViewSet(viewsets.ModelViewSet):
    queryset = GeneroEscrito.objects.all()
    serializer_class = GeneroEscritoSerializer

class GeneroMedioDigitalViewSet(viewsets.ModelViewSet):
    queryset = GeneroMedioDigital.objects.all()
    serializer_class = GeneroMedioDigitalSerializer

class GeneroRadioViewSet(viewsets.ModelViewSet):
    queryset = GeneroRadio.objects.all()
    serializer_class = GeneroRadioSerializer

class FuenteViewSet(viewsets.ModelViewSet):
    queryset = Fuente.objects.all()
    serializer_class = FuenteSerializer

class ArticuloViewSet(viewsets.ModelViewSet):
    queryset = Articulo.objects.all()
    serializer_class = ArticuloSerializer

class EmpresarioViewSet(viewsets.ModelViewSet):
    queryset = Empresario.objects.all()
    serializer_class = EmpresarioSerializer

class EjecutivoViewSet(viewsets.ModelViewSet):
    queryset = Ejecutivo.objects.all()
    serializer_class = EjecutivoSerializer

class AutorViewSet(viewsets.ModelViewSet):
    queryset = Autor.objects.all()
    serializer_class = AutorSerializer

def get_nombre(request):
    if request.method == 'POST':
    	form = ContactoForm(request.POST)
    	if form.is_valid():
    		su_nombre = form.cleaned_data['su_nombre']
    		asunto = form.cleaned_data['asunto']
    		mensaje = form.cleaned_data['mensaje']
    		email = form.cleaned_data['email']
    		cc_myself = form.cleaned_data['cc_myself']
    		recipients = ['felipe.perry@gmail.com','miguel@poderopedia.com']
    		if cc_myself:
    			recipients.append(email)
    			send_mail(asunto, mensaje, email, recipients)
    			return HttpResponseRedirect('medioschile/gracias/')
    		else:
    			form = ContactoForm()
    			return render(request, 'medioschile/contacto.html', {'form': form})

templates/medioschile/analisis_listcl.html
{% extends "medioschile/base.html" %}
{% block content %}
<section class="section-title row-module">
      <div class="row">
        <div class="col16">
          <div class="heading acenter">
            <h1>Análisis</h1>
            <h2>Posteos a partir de los datos de Mapa de Medios</h2>
          </div>
        </div>
      </div>
    </section>

    <section class="section-subtitle">
      <div class="row">
        <div class="col4">
          <span class="label">{{ analisiscl.count }} posteos sobre Chile</span>
        </div>
        <div class="col12 clearfix">
          <div class="btn-group right">
            <ul>
              <li class="dropdown dropdown-nav">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle btn btn-s btn-link btn-outline btn-info"><i class="icon icon-16 flaticon solid earth-1"></i> País <span class="arrow"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'medioschile:analisiscl' %}">Chile</a></li>
                  <li><a href="{% url 'medioschile:analisiscol' %}">Colombia</a></li>
                </ul>
              </li>
              <li class="dropdown dropdown-nav">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle btn btn-s btn-link btn-outline btn-info"><i class="icon icon-16 flaticon solid tag-1"></i> Etiqueta <span class="arrow"></span></a>
                <ul class="dropdown-menu">
                {% for tag in etiqueta %}
                  <li><a href="#">{{ tag.etiqueta }}</a></li>
                {% endfor %}
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>

    <section class="section-article list row-module">
      <div class="row">
        <div class="col12 prefix2">
        {% for articulo in analisiscl %}
          <article class="post">
            <div class="post-title">
              <h3><a href="{{ articulo.pk }}">{{ articulo.titulo }}</a></h3>
              <div class="post-metadatos">
                <ul>
                  <li class="with-icon"><i class="icon icon-16 flaticon solid clock-1"></i> Publicado en {{ articulo.fecha }}</li>
                  <li>por {{ articulo.autor }}</li>
                </ul>
              </div>
            </div>
            <div class="post-body text">
              <figure>
                <img src="{{ MEDIA_URL }}{{ articulo.imagen_destacada }}" />
              </figure>
              <p>{{ articulo.extracto }}</p>
            </div>
          </article>
        {% endfor %}

        </div>
      </div>

    </section>

{% endblock %}

templates/medioschile/fuente_list.html
{% extends "medioschile/base.html" %}
{% block content %}
<section class="section-title row-module row-module-s-bottom">
    <div class="row">
      <div class="col16">
        <div class="heading acenter">
          <h1>Fuentes</h1>
          <h2>Listado de fuentes consultadas para hacer el mapa de la industria de medios de Chile. <br><a href="/medioschile/datos">Descarga los datos</a>.
        </div>
      </div>
    </div>
</section>

<section class="row-module row-module-s-top">
    <div class="row">
      <div class="col16">

<table id="TablaLista" class="display" width="100%" cellspacing="0">

    <thead>
    <tr>
    <th width="40%" align="left">Fuente</th>
    <th width="40%" align="left">Descripción</th>
    <th width="20%" align="left">URL de la fuente</th>
    </tr>
    </thead>

    <tbody>
    {% for fuente in fuente_list %}
        <tr>
        <td>{{ fuente.fuente | default:"No hay información" }}</a></td>
        <td>{{ fuente.descripcion | default:"No hay información" }}</td>
        <td>{% if fuente.linkfuente %}<a href="{{ fuente.linkfuente }}">{{ fuente.linkfuente | truncatechars:20 }}</a>{% else %}No hay información{% endif %}</td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="5">
            </td>
        </tr>
    </tfoot>
    </table>
      </div>
    </div>
</section>

{% endblock %}

templates/medioschile/index.html
{% extends "medioschile/base.html" %}
{% load medioschile_extras %}
{% load medioscolombia_extras %}
{% block content %}
<section class="section-featured row-module">
    <div class="row">
      <div class="col16">
        <div class="heading acenter">
          <h1>Descubre quién es quién en la Industria de medios de Chile y Colombia.</h1>
          <p>El Mapa de Medios es una base de datos de Medios de Comunicación de <a href=".">Chile</a> y <a href="{% url 'medioscolombia:index' %}">Colombia</a>, y quiénes son los propietarios de esos Medios. Incluye la mayor parte de los Medios Impresos, Digitales, Radiales y Televisivos de cada país un registro de cuáles son las leyes relativas a Medios y el ejercicio del Periodismo; y las fuentes de información consultadas para realizar esta investigación. Conoce el analisis, descarga los <a href="{% url 'medioschile:datos' %}">Datos</a>, usa la <a href="{% url 'api' %}">API</a>, revisa la <a href="{% url 'medioschile:metodologia' %}">Metodología</a> y reutiliza el <a href="{% url 'medioschile:codigo' %}">Código</a> de esta aplicación.</p>
        </div>
      </div>
      <div class="col12 prefix2">
    <form class="form-search" action="/search" method="GET">
            <div class="search-group">
              <div class="search-form">
                <i class="icon icon-16 flaticon stroke zoom-2"></i>
                <input type="text" name="q" placeholder="Buscar por el nombre del medio, propietario o grupo de medios" />
              </div>
              <div class="search-submit">
                <input type="submit" class="btn btn-m btn-primary" value="Buscar" />
              </div>
            </div>
            <!-- <div class="form-search-options">
              <label class="radio"><input type="radio" name="checkpais" value="cl" checked="checked"> Chile</label>
              <label class="radio"><input type="radio" name="checkpais" value="col"> Colombia</label>
              <p><i class="icon icon-16 flaticon solid question-2"></i> Selecciona el País donde quieres buscar.</p>
            </div> -->
    </form>
      </div>
    </div>
  </section>

  <section class="section-articles row-module">
    <div class="row">
      <div class="col16">
        <div class="heading acenter">
          <h3>Análisis</h3>
        </div>
      </div>

      <div id="slide-articles" class="carousel" data-ride="carousel" data-interval="false">
        <div class="carousel-inner" role="listbox">
          <div class="item active">
            <article class="col8">
            {% for articulo in articulos %}
            {% if articulo.posicion == "1" %}
              <a href="{% url 'medioschile:analisisdetail' articulo.pk %}">
                <h3>{{ articulo.titulo }}</h3>
                <figure>
                  <img src="{{ MEDIA_URL }}{{ articulo.imagen_destacada }}" />
                </figure>
                <span class="btn btn-s btn-default">
                  <i class="icon icon-16 flaticon stroke activity-1"></i> Leer
                </span>
              </a>
            {% endif %}
            {% endfor %}
            </article>
           
            <article class="col8">
            {% for articulo in articulos %}
            {% if articulo.posicion == "2" %}
              <a href="{% url 'medioschile:analisisdetail' articulo.pk %}">
                <h3>{{ articulo.titulo }}</h3>
                <figure>
                  <img src="{{ MEDIA_URL }}{{ articulo.imagen_destacada }}" />
                </figure>
                <span class="btn btn-s btn-default">
                  <i class="icon icon-16 flaticon stroke activity-1"></i> Leer
                </span>
              </a>
            {% endif %}
            {% endfor %}
            </article>
          </div><!--/item-->

          <div class="item">
            <article class="col8">
            {% for articulo in articulos %}
            {% if articulo.posicion == "3" %}
              <a href="{% url 'medioschile:analisisdetail' articulo.pk %}">
                <h3>{{ articulo.titulo }}</h3>
                <figure>
                  <img src="{{ MEDIA_URL }}{{ articulo.imagen_destacada }}" />
                </figure>
                <span class="btn btn-s btn-default">
                  <i class="icon icon-16 flaticon stroke activity-1"></i> Leer
                </span>
              </a>
            {% endif %}
            {% endfor %}
            </article>

            <article class="col8">
            {% for articulo in articulos %}
            {% if articulo.posicion == "4" %}
              <a href="{% url 'medioschile:analisisdetail' articulo.pk %}">
                <h3>{{ articulo.titulo }}</h3>
                <figure>
                  <img src="{{ MEDIA_URL }}{{ articulo.imagen_destacada }}" />
                </figure>
                <span class="btn btn-s btn-default">
                  <i class="icon icon-16 flaticon stroke activity-1"></i> Leer
                </span>
              </a>
            {% endif %}
            {% endfor %}
            </article>
          </div><!--/item-->
        </div>

        <a href="#slide-articles" class="ctrl prev" data-slide="prev">Previous</a>
        <a href="#slide-articles" class="ctrl next" data-slide="next">Next</a>

        <ol class="carousel-indicators">
          <li data-target="#slide-articles" data-slide-to="0" class="active">1</li>
          <li data-target="#slide-articles" data-slide-to="1">2</li>
        </ol>

      </div><!--/slide articles-->

    </div>
  </section>

  <section class="section-categories row-module"><a name="categorias"></a>
    <div class="row">
      <div class="col16">
        <div class="heading acenter">
          <h3>Descubre información por categorías</h3>
        </div>
      </div>
      <div class="col7">
        <h6><i class="icon icon-16 flaticon solid tag-1"></i> Medios de Chile</h6>
        <nav>
          <ul>
            <li><a href="{% url 'medioschile:digitaleslist' %}"><span>{% contardigitales %}</span>Medios Digitales</a></li>
            <li><a href="{% url 'medioschile:escritoslist' %}"><span>{% contarescritos %}</span>Impresos</a></li>
            <li><a href="{% url 'medioschile:canalestvlist' %}"><span>{% contarcanalestv %}</span>Televisión</a></li>
            <li><a href="{% url 'medioschile:radioslist' %}"><span>{% contarradios %}</span>Radio</a></li>
            <li><a href="{% url 'medioschile:gruposlist' %}"><span>{% contargrupos %}</span>Grupos de Medios</a></li>
            <li><a href="{% url 'medioschile:propietarioslist' %}"><span>{% contarpropietarios %}</span>Propietarios</a></li>
            <li><a href="{% url 'medioschile:regulacioneslist' %}"><span>{% contarleyes %}</span>Legislación</a></li>
            <li><a href="{% url 'medioschile:fuenteslist' %}"><span>{% contarfuentes %}</span>Fuentes Utilizadas</a></li>
          </ul>
        </nav>
      </div>
      <div class="col7 prefix2">
        <h6><i class="icon icon-16 flaticon solid tag-1"></i> Medios de Colombia</h6>
        <nav>
          <ul>
            <li><a href="{% url 'medioscolombia:digitaleslist' %}"><span>{% contardigitalescol %}</span>Medios Digitales</a></li>
            <li><a href="{% url 'medioscolombia:escritoslist' %}"><span>{% contarescritoscol %}</span>Impresos</a></li>
            <li><a href="{% url 'medioscolombia:canalestvlist' %}"><span>{% contarcanalestvcol %}</span>Televisión</a></li>
            <li><a href="{% url 'medioscolombia:radioslist' %}"><span>{% contarradioscol %}</span>Radio</a></li>
            <li><a href="{% url 'medioscolombia:gruposlist' %}"><span>{% contargruposcol %}</span>Grupos de Medios</a></li>
            <li><a href="{% url 'medioscolombia:propietarioslist' %}"><span>{% contarpropietarioscol %}</span>Propietarios</a></li>
            <li><a href="{% url 'medioscolombia:regulacioneslist' %}"><span>{% contarleyescol %}</span>Legislación</a></li>
            <li><a href="{% url 'medioscolombia:fuenteslist' %}"><span>{% contarfuentescol %}</span>Fuentes Utilizadas</a></li>
          </ul>
        </nav>
      </div>
    </div>
  </section>

  <section class="row-module">
    <div class="row">
      <div class="col16">
        <div class="heading acenter">
          <h3>Conoce la metodología y <br/> reusa la información en tu proyecto</h3>
        </div>

        <div class="item-featured-list">
          <div class="item-featured">
            <a href="{% url 'medioschile:acercade' %}">
              <span>
                <i class="icon icon-32 flaticon solid open-book-1"></i>
              </span>
              <h6>Qué es el Mapa de Medios</h6>
              <p>El Mapa de Medios de Chile y Colombia es una base de datos sobre la industria de medios en estos países, sus dueños, actores que inciden en las políticas públicas y la legislación sobre los medios de comunicación.</p>
            </a>
          </div>
          <div class="item-featured">
            <a href="{% url 'medioschile:metodologia' %}">
              <span>
                <i class="icon icon-32 flaticon solid magic-wand-1"></i>
              </span>
              <h6>Cómo de hizo</h6>
              <p>Mapa de Medios de Chile y Colombia es el resultado de una investigación periodística, dos hackdays realizados en cada país donde se asistieron académicos, expertos, periodistas, diseñadores y programadores, quienes colaboraron en la construcción de una base de datos.</p>
            </a>
          </div>
          <div class="item-featured">
            <a href="{% url 'medioschile:datos' %}">
              <span>
                <i class="icon icon-32 flaticon solid download-1"></i>
              </span>
              <h6>Descarga los datos</h6>
              <p>Los datos recopilados en Mapa de Medios están disponibles para la comunidad (ciudadanos, estudiantes, investigadores, etc.) bajo una estructura de Open Data.</p>
            </a>
          </div>
          <div class="item-featured">
            <a href="{% url 'medioschile:codigo' %}">
              <span>
                <i class="icon icon-32 flaticon social github-1"></i>
              </span>
              <h6>Código abierto para tu proyecto</h6>
              <p>Este proyecto está construido sobre la aplicación de ingreso y publicación de datos de código abierto MediaMapper. Revisa cómo puedes crear tu propio proyecto sobre Medios.</p>
            </a>
          </div>
          <div class="item-featured">
            <a href="{% url 'api' %}">
              <span>
                <i class="icon icon-32 flaticon solid settings-2"></i>
              </span>
              <h6>Tenemos API</h6>
              <p>Si necesitas reutilizar nuestros datos en tiempo real, para tus aplicaciones o sitios web, tenemos API disponible. Puedes integrar Mapa de Medios a tus proyectos y te podemos ayudar si lo requieres.</p>
            </a>
          </div>
          <div class="item-featured">
            <a href="{% url 'medioschile:aporta' %}">
              <span>
                <i class="icon icon-32 flaticon solid mail-3"></i>
              </span>
              <h6>Agrega nueva información de Medios</h6>
              <p>Mapa de Medios permite a los usuarios aportar contenido a sus bases de datos a fin de incrementar la información y actualizaciones relativas a la propiedad de los medios de comunicación en Chile y Colombia.</p>
            </a>
          </div>
        </div>

      </div>
    </div>
  </section>

{% endblock %}