mediamapper/urls.py
from django.http import HttpResponse
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS admin
    url(r'^admin/',  include(admin.site.urls)), # admin site
    url(r'^select2/', include('select2.urls')), # select2 multiselect admin
    url(r'^home/', view=TemplateView.as_view(template_name="medioschile/index.html"), name='home'),
    url(r'^api/', view=TemplateView.as_view(template_name="api.html"), name='api'),
    url(r'^medioschile/', include('medioschile.urls', namespace='medioschile')), # medioschile
    url(r'^medioscolombia/', include('medioscolombia.urls', namespace='medioscolombia')), # medioscolombia
    url(r'^redactor/', include('redactor.urls')), # redactor editor
    url(r'^search/', include('haystack.urls')),

)	+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medioschile/urls.py
from . import views
from django.conf.urls import patterns, url, include
from django.conf.urls.static import static
from rest_framework import routers
from medioschile import serializers

router = routers.DefaultRouter()
router.register(r'propietarios', views.PropietarioViewSet)
router.register(r'sociedades', views.SociedadViewSet)
router.register(r'tiposociedades', views.TipoSociedadViewSet)
router.register(r'grupos', views.GrupoViewSet)
router.register(r'paises', views.PaisSociedadViewSet)
router.register(r'fuentes', views.FuenteViewSet)
router.register(r'escritos', views.EscritoViewSet)
router.register(r'canaltvs', views.CanalTVViewSet)
router.register(r'generoradios', views.GeneroRadioViewSet)
router.register(r'generoescritos', views.GeneroEscritoViewSet)
router.register(r'generocanaltvs', views.GeneroCanalTVViewSet)
router.register(r'generomediodigitales', views.GeneroMedioDigitalViewSet)
router.register(r'radios', views.RadioViewSet)
router.register(r'mediodigitales', views.MedioDigitalViewSet)
router.register(r'ejecutivos', views.EjecutivoViewSet)
router.register(r'empresarios', views.EmpresarioViewSet)
router.register(r'articulos', views.ArticuloViewSet)
router.register(r'autores', views.AutorViewSet)

urlpatterns = [
	url(r'^index/$', 'medioschile.views.index', name='index'),
    url(r'^acercade/$', 'medioschile.views.acercade', name='acercade'),
	url(r'^consultadirecta/$', 'medioschile.views.consultadirecta', name='consultadirecta'),
    url(r'^metodologia/$', 'medioschile.views.metodologia', name='metodologia'),
    url(r'^privacidad/$', 'medioschile.views.privacidad', name='privacidad'),
    url(r'^datos/$', 'medioschile.views.datos', name='datos'),
    url(r'^codigo/$', 'medioschile.views.codigo', name='codigo'),
    url(r'^contacto/$', 'medioschile.views.contacto', name='contacto'),
    url(r'^aporta/$', 'medioschile.views.aporta', name='aporta'),
    url(r'^analisiscl/$', 'medioschile.views.analisiscl', name='analisiscl'),
    url(r'^analisiscol/$', 'medioschile.views.analisiscol', name='analisiscol'),
    url(r'^fuente/$', views.FuenteList.as_view(), name='fuenteslist'),
    url(r'^analisis/$', views.AnalisisList.as_view(), name='analisislist'),
    url(r'^analisis/(?P<pk>\d+)/$', views.AnalisisDetail.as_view(), name='analisisdetail'),
    url(r'^regulacion/$', views.RegulacionList.as_view(), name='regulacioneslist'),
    url(r'^regulacion/(?P<pk>\d+)/$', views.RegulacionDetail.as_view(), name='regulaciondetail'),
    url(r'^grupo/(?P<pk>\d+)/$', views.GrupoDetail.as_view(), name='grupodetail'),
    url(r'^grupo/$', views.GrupoList.as_view(), name='gruposlist'),
    url(r'^propietario/$', views.PropietarioList.as_view(), name='propietarioslist'),
    url(r'^propietario/(?P<pk>\d+)/$', views.PropietarioDetail.as_view(), name='propietariodetail'),
    url(r'^escritolist/$', views.EscritoList.as_view(), name='escritoslist'),
    url(r'^escritolist/(?P<pk>\d+)/$', views.EscritoDetail.as_view(), name='escritodetail'),
    url(r'^canaltvlist/$', views.CanalTVList.as_view(), name='canalestvlist'),
    url(r'^canaltvlist/(?P<pk>\d+)/$', views.CanalTVDetail.as_view(), name='canaltvdetail'),
    url(r'^radiolist/$', views.RadioList.as_view(), name='radioslist'),
    url(r'^radiolist/(?P<pk>\d+)/$', views.RadioDetail.as_view(), name='radiodetail'),
    url(r'^mediodigitallist/$', views.MedioDigitalList.as_view(), name='digitaleslist'),
    url(r'^mediodigitallist/(?P<pk>\d+)/$', views.MedioDigitalDetail.as_view(), name='digitaldetail'),
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

templates/search/search-2.html
{% extends "medioschile/base.html" %}
{% load medioschile_extras %}
{% load medioscolombia_extras %}
{% block content %}
    <section class="section-title row-module row-module-s-bottom">
      <div class="row">
        <div class="col16">
          <div class="heading">
          <h1>Resultado de búsqueda</h1>
          <h2>{{ page.object_list|length }} Resultados para <span class="search-results-close">“{{ query }}”</span></h2>
          </div>
        </div>
      </div>
    </section>
    <section class="row-module row-module-s-top">
      <div class="row">
        <div class="col16">
    {% if query %}
      {% for result in page.object_list %}
        {% with result.object|appname as modelapp %}
          {% if modelapp == "medioschile" %}
            {% with result.object|classname as modelclass %}
              <table class="display dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                <th width="25%" align="left"></th>
                <th width="25%" align="left"></th>
                <th width="50%" align="left"></th>
                </tr>
              </thead>
              <tbody>

            {% if modelclass == "Escrito" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:escritodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">
                    <span class="badge badge-medio badge-magazine">Medio Impreso</span>
                </td>
              </tr>
              
            {% elif modelclass == "CanalTV" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:canaltvdetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-tv">Canal de TV</span>                 
                </td>
              </tr>

            {% elif modelclass == "Radio" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:radiodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-radio">Radio</span>            
                </td>
              </tr>

            {% elif modelclass == "MedioDigital" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:digitaldetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-digital">Medio Digital</span>            
                </td>
              </tr>
                
            {% elif modelclass == "Propietario" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}medios/business.png" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:propietariodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">
                  <span class="badge badge-empresa">Propietario de Medios</span>
                </td>
              </tr>
                
            {% elif modelclass == "Grupo" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}medios/business.png" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:grupodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                  <span class="badge badge-empresa">Grupo de Medios</span>
                </td>
              </tr>

            {% endif %}

            </tbody>
            </table>
            {% endwith %}
          
          {% elif modelapp == "medioscolombia" %}

            {% with result.object|classname as modelclass %}
              <table class="display dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                <th width="25%" align="left"></th>
                <th width="25%" align="left"></th>
                <th width="50%" align="left"></th>
                </tr>
              </thead>
              <tbody>

            {% if modelclass == "Escrito" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:escritodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">
                    <span class="badge badge-medio badge-magazine">Medio Impreso</span>
                </td>
              </tr>
              
            {% elif modelclass == "CanalTV" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:canaltvdetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-tv">Canal de TV</span>                 
                </td>
              </tr>

            {% elif modelclass == "Radio" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:radiodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-radio">Radio</span>            
                </td>
              </tr>

            {% elif modelclass == "MedioDigital" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:digitaldetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-digital">Medio Digital</span>            
                </td>
              </tr>
                
            {% elif modelclass == "Propietario" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}medios/business.png" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:propietariodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">
                  <span class="badge badge-empresa">Propietario de Medios</span>
                </td>
              </tr>
                
            {% elif modelclass == "Grupo" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}medios/business.png" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:grupodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                  <span class="badge badge-empresa">Grupo de Medios</span>
                </td>
              </tr>

            {% endif %}

            </tbody>
            </table>
            {% endwith %}

      {% endif %}
          
          
          
        {% endwith %}<!-- 5 -->
      {% empty %}<!-- 3 -->
          <h3>Su búsqueda no ha dado resultados, intente <a href="/medioschile/index/#categorias">revisando por categorías</a></h3>
      {% endfor %}<!-- 2 -->


    {% endif %}<!-- 1 --> 

      </div>
    </div>
  </section>

{% endblock %}

templates/search/search-l.html
{% extends "medioschile/base.html" %}
{% load medioschile_extras %}
{% load medioscolombia_extras %}
{% block content %}
    <section class="section-title row-module row-module-s-bottom">
      <div class="row">
        <div class="col16">
          <div class="heading">
          <h1>Resultado de búsqueda</h1>
          <h2>{{ page.object_list|length }} Resultados para <span class="search-results-close">“{{ query }}”</span></h2>
          </div>
        </div>
      </div>
    </section>
    <section class="row-module row-module-s-top">
      <div class="row">
        <div class="col16">
    {% with page.object_list as modelapp %}
            {% regroup modelapp|dictsort:"verbose_name_plural" by verbose_name_plural as grouped_objects %}
            {% for ct in grouped_objects %}
                {{ ct.grouper }}
                {% for result in ct.list %}
                    <p>
                        <a href="{{ result.object.get_absolute_url }}">{{ result.object }}</a>
                    </p>
                {% endfor %}
            {% empty %}
                <p>No results found.</p>
            {% endfor %}
    {% endwith %}

      </div>
    </div>
  </section>

{% endblock %}

templates/search/search.html
{% extends "medioschile/base.html" %}
{% load medioschile_extras %}
{% load medioscolombia_extras %}
{% block content %}
    <section class="section-title row-module row-module-s-bottom">
      <div class="row">
        <div class="col16">
          <div class="heading">
          <h1>Resultado de búsqueda</h1>
          <h2>{{ page|length }} Resultados para <span class="search-results-close">“{{ query }}”</span></h2>
          </div>
        </div>
      </div>
    </section>
    <section class="row-module row-module-s-top">
      <div class="row">
        <div class="col16">
          {% if query %}
          {% for result in page %}
          {% if result.object.app == "Chile" %}
          {{ result.object.app }}
          {% elif result.object.app == "Colombia" %}
          {{ result.object.app }}
          {% endif %}
          {% endfor %}
          {% endif %}
        </div>
        <!-- <div class="col16">
    {% if query %}
      {% for result in page.object_list %}
        {% with result.object|appname as modelapp %}
          {% if modelapp == "medioschile" %}
            {% with result.object|classname as modelclass %}
              <table class="display dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                <th width="25%" align="left"></th>
                <th width="25%" align="left"></th>
                <th width="50%" align="left"></th>
                </tr>
              </thead>
              <tbody>

            {% if modelclass == "Escrito" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:escritodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">
                    <span class="badge badge-medio badge-magazine">Medio Impreso</span>
                </td>
              </tr>
              
            {% elif modelclass == "CanalTV" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:canaltvdetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-tv">Canal de TV</span>                 
                </td>
              </tr>

            {% elif modelclass == "Radio" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:radiodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-radio">Radio</span>            
                </td>
              </tr>

            {% elif modelclass == "MedioDigital" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:digitaldetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-digital">Medio Digital</span>            
                </td>
              </tr>
                
            {% elif modelclass == "Propietario" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}medios/business.png" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:propietariodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">
                  <span class="badge badge-empresa">Propietario de Medios</span>
                </td>
              </tr>
                
            {% elif modelclass == "Grupo" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}medios/business.png" width="25px"/></td>
                <td align="left"><a href="{% url 'medioschile:grupodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                  <span class="badge badge-empresa">Grupo de Medios</span>
                </td>
              </tr>

            {% endif %}

            </tbody>
            </table>
            {% endwith %}
          
          {% elif modelapp == "medioscolombia" %}

            {% with result.object|classname as modelclass %}
              <table class="display dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                <th width="25%" align="left"></th>
                <th width="25%" align="left"></th>
                <th width="50%" align="left"></th>
                </tr>
              </thead>
              <tbody>

            {% if modelclass == "Escrito" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:escritodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">
                    <span class="badge badge-medio badge-magazine">Medio Impreso</span>
                </td>
              </tr>
              
            {% elif modelclass == "CanalTV" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:canaltvdetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-tv">Canal de TV</span>                 
                </td>
              </tr>

            {% elif modelclass == "Radio" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:radiodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-radio">Radio</span>            
                </td>
              </tr>

            {% elif modelclass == "MedioDigital" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}{{ result.object.logo }}" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:digitaldetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                    <span class="badge badge-medio badge-digital">Medio Digital</span>            
                </td>
              </tr>
                
            {% elif modelclass == "Propietario" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}medios/business.png" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:propietariodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">
                  <span class="badge badge-empresa">Propietario de Medios</span>
                </td>
              </tr>
                
            {% elif modelclass == "Grupo" %}
              <tr>
                <td align="left"><img class="img-circle" src="{{ MEDIA_URL }}medios/business.png" width="25px"/></td>
                <td align="left"><a href="{% url 'medioscolombia:grupodetail' result.object.pk %}">{{ result.object }}</a></td>
                <td align="left">                  
                  <span class="badge badge-empresa">Grupo de Medios</span>
                </td>
              </tr>

            {% endif %}

            </tbody>
            </table>
            {% endwith %}

      {% endif %}
          
          
          
        {% endwith %}
      {% empty %}
          <h3>Su búsqueda no ha dado resultados, intente <a href="/medioschile/index/#categorias">revisando por categorías</a></h3>
      {% endfor %}


    {% endif %}

      </div>-->
    </div>
  </section>

{% endblock %}